# -*- coding: utf-8 -*-
"""ADHDcode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ql-kxagMFXC_3jHa4wOc-OvLr10icc9C
"""

# Install experta (may install outdated dependencies)
!pip install experta

# Upgrade frozendict to a compatible version, overwriting the old one
!pip install frozendict --upgrade

#!/usr/bin/env python
from experta import *

# ============================================
# Expert System: ADHD (Inattentive Type)
# ============================================

# -----------------------------
# Knowledge Base (KB)
# -----------------------------
# Static question data remains outside the engine
symptoms_questions = [
    "Do you often forget tasks or misplace personal items?",
    "Do you find it difficult to stay focused during work or study?",
    "Do you become easily distracted by surroundings?",
    "Do you have trouble following detailed instructions?",
    "Do you avoid or dislike tasks requiring long mental effort?",
    "Do you frequently make careless mistakes in work or school?",
    "Do you forget daily routines (like bringing materials or personal items)?",
    "Do you struggle to organize tasks and activities?",
    "Do you seem not to listen even when spoken to directly?",
    "Do you start tasks but fail to complete them?",
    "Do you overlook important details when reading or listening?",
    "Do you have difficulty keeping track of time or meeting deadlines?"
]

additional_questions = {
    "multiple_settings": "Do these symptoms occur in multiple settings (e.g., home, school, work)?",
    "duration_months": "For how many months have these symptoms been present? ",
    "only_during_stress": "Do these symptoms occur only during stress or sleep deprivation?",
    "sudden_adult_onset": "Did these symptoms appear suddenly in adulthood without prior history?"
}

# Helper function for clean input
def ask_yes_no(question):
    """Prompts for 'y' or 'n' and returns a boolean."""
    answer = input(question + " ('y' for yes/'n' for no): ").strip().lower()
    return answer in ["y", "yes"]

# -----------------------------
# Expert System Engine
# -----------------------------
class ADHDExpertSystem(KnowledgeEngine):
    """
    An expert system to evaluate the likelihood of
    ADHD (Inattentive Type) based on user-provided facts.
    """

    @DefFacts()
    def _get_initial_facts(self):
        """
        Gathers all required facts from the user at startup.
        """
        print("===================================")
        print(" ADHD Inattentive Type Expert System ")
        print("===================================\n")

        # Step 1: Enter age
        yield Fact(age=int(input("Enter age: ")))

        # Step 3: Ask 12 core symptoms and count
        print("\nPlease answer yes/no to the following symptoms:")
        current_symptoms = 0
        for question in symptoms_questions:
            if ask_yes_no(question):
                current_symptoms += 1
        yield Fact(symptom_count=current_symptoms)

        # Step 4: Ask 4 additional questions
        print("\nAnswer the following additional questions:")
        yield Fact(only_during_stress=ask_yes_no(additional_questions["only_during_stress"]))
        yield Fact(sudden_adult_onset=ask_yes_no(additional_questions["sudden_adult_onset"]))
        yield Fact(multiple_settings=ask_yes_no(additional_questions["multiple_settings"]))
        yield Fact(duration_months=int(input(additional_questions["duration_months"])))

        # This fact will hold the final result
        yield Fact(result_summary=None)

    # -----------------------------
    # Decision Rules
    # -----------------------------

    @Rule(Fact(age=W('age')),
          salience=110) # High priority: needed for other rules
    def determine_min_symptoms(self, age):
        """Determine the minimum symptom threshold based on age."""
        min_symptoms = 5 if age >= 17 else 6
        self.declare(Fact(min_symptoms=min_symptoms))

    # --- Exclusion Rules (High Salience) ---
    # These rules run first to check for immediate exclusions.

    @Rule(Fact(only_during_stress=True),
          salience=100)
    def rule_exclusion_stress(self):
        self.declare(Fact(diagnosis="Unlikely ADHD (Situational factors)"))

    @Rule(Fact(sudden_adult_onset=True),
          salience=90)
    def rule_exclusion_sudden_onset(self):
        self.declare(Fact(diagnosis="Possible other condition, seek clinical evaluation"))

    @Rule(Fact(multiple_settings=False),
          salience=80)
    def rule_exclusion_one_setting(self):
        self.declare(Fact(diagnosis="ADHD unlikely or insufficient evidence (Symptoms appear in only one setting)"))

    @Rule(Fact(duration_months=L(lambda x: x < 6)),
          salience=70)
    def rule_exclusion_short_duration(self):
        self.declare(Fact(diagnosis="ADHD unlikely or insufficient evidence (Symptoms present for less than 6 months)"))

    # --- Diagnosis Rules (Low Salience) ---
    # These rules run only if no exclusion rules have fired.

    @Rule(Fact(symptom_count=W('count')),
          Fact(min_symptoms=W('min_req')),
          Fact(age=W('age')),
          TEST(lambda count, min_req: count >= min_req),
          NOT(Fact(diagnosis=W())),  # Only run if no diagnosis has been made
          salience=10)
    def rule_diagnose_likely_adhd(self, age):
        """Diagnose likely ADHD if symptoms meet the threshold."""
        diag_text = "Likely ADHD, Inattentive Type (Adult)" if age >= 17 else "Likely ADHD, Inattentive Type (Child / Adolescent)"
        self.declare(Fact(diagnosis=diag_text))

    @Rule(Fact(symptom_count=W('count')),
          Fact(min_symptoms=W('min_req')),
          TEST(lambda count, min_req: count < min_req),
          NOT(Fact(diagnosis=W())), # Only run if no diagnosis has been made
          salience=9)
    def rule_diagnose_unlikely_insufficient_symptoms(self):
        """Diagnose as unlikely if symptoms are below the threshold."""
        self.declare(Fact(diagnosis="ADHD unlikely or insufficient evidence"))

    # --- Output Rule (Lowest Salience) ---
    # This rule fires last to print the final summary.

    @Rule(Fact(diagnosis=W('diagnosis')),
          Fact(symptom_count=W('count')),
          Fact(min_symptoms=W('min_req')),
          Fact(result_summary=None), # Only run once
          salience=-10)
    def print_result(self, diagnosis, count, min_req):
        """Formats and prints the final assessment."""

        summary = (
            "\n----- ADHD Assessment Result -----\n"
            f"Diagnosis: {diagnosis}\n"
            f"Total reported symptoms: {count}\n"
            f"Minimum required symptoms: {min_req}\n"
            "===================================\n"
            "Thank you for using the Expert System for ADHD (Inattentive Type).\n"
            "For accurate assessment and personalized advice, it’s always best to consult a qualified medical professional.\n"
            "===================================\n"
        )
        print(summary)
        # Modify the fact to prevent this rule from firing again
        self.modify(self.facts[1], result_summary=summary)


# -----------------------------
# Main Execution
# -----------------------------
if __name__ == "__main__":
    engine = ADHDExpertSystem()
    engine.reset()
    engine.run()
